name: Node.js CI

on:
  [pull_request]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
    - run: npm run coverage
      if: matrix.node != '10.x'
      
    - name: Test without coverage
      if: matrix.node == '10.x'
      run: |
           npm install -D esm
           npx mocha -r esm 
